<?php

namespace AppBundle\Repository\Tasks;

use Doctrine\ORM\EntityRepository;

/**
 * ProjectsRepository
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
class ProjectsRepository extends EntityRepository
{
}
