# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:

    app.settings_authenticator:
        class: AppBundle\AuthService\SettingAuth
        arguments: ["@doctrine.orm.default_entity_manager", "@router"]
        

#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
